services:
  link-feed:
    build:
      context: .
      dockerfile: Dockerfile
    image: link-feed:latest
    container_name: link-feed
    environment:
      # Automatically loads variables from the .env file located in the same directory as this file
      - DATABASE_URL=sqlite:///inputs.db
      - SECRET_KEY=replaceme
      - EXPORTS_DIRECTORY=exports
      - ALLOW_REGISTRATION=true
      - MODE=development
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    volumes:
      # mount the local directory for development
      - .:/app